repository: InsightfunShare/BYR-Navi
repository_url: https://github.com/InsightfunShare/BYR-Navi

timezone: Asia/Shanghai
lang: zh_CN

title: 集智芬享 · AI导航
alias_en: InsightfunShare-Nav
alias_cn: 集智芬享导航
description: A Navigation Website for InsightfunShare
keywords: 集智芬享导航, InsightfunShare-Nav, JZFX, Nav, Navigation, AI, ChatGPT, Chat, AI导航, AI, 导航
url: https://aigear.pp.ua/
established_at: "2025-07-02T00:00+08:00"

author: 集智芬享
author_url: https://jzfx.de
organization: InsightfunShare
organization_url: https://jzfx.de
contact: contact[at]jzfx[dot]de

image: /images/logo.png
logo: /images/logo.png
logo_dark: /images/logo-dark.svg
logo_white: /images/logo-white.svg

update_interval: 60000

plugins:
- jekyll-seo-tag
- jekyll-sitemap

exclude:
- .gitignore
- .travis.yml
- LICENSE
- README.md
- CNAME
- Gemfile
- Gemfile.lock
- script
- vendor